# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e0a6cbafff643e660a74ff958cd10773ef2c9b89fd2c28b2d6500a877b6eaf09485cb773bbd20f0665689be5da0e503fc1f4c541b98cba9ae99fc636ae294b

test:
  secret_key_base: 78cf3b38b10e4e063d43fcc58c6f016928ba8814eeeca6413d24e66c059dfe283735c419e6986de26ff7cb059d279aad5f2c64a67745c1fb632c8c33bccad5c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
